### ISSUE TITLE
cplace-asc creates abnormally high cpu usage after compilation in watch mode

### ISSUE THREAD

**Issue by stefancplace** [collaborationFactory/cplace-asc#30]
After compilation and bundling of all assets, asc consumes abnormally high cpu usage in watch mode

**Comment by rose-m** [comment]
Is this still reproducible otherwise we'll close it. No further reports received...

**Comment by stefancplace** [comment]
Thomas Büchner said he doesnt experience it anymore
Although on executing circleci workflows locally via Docker I have the feeling cplace-asc crashes the build process using excessive amounts of ressources...
