### ISSUE TITLE
Compilation errors on cplace forks with custom names

### ISSUE THREAD

**Issue by borisdries** [collaborationFactory/cplace-asc#9]
If the cplace main repository was forked, the name has to be set to `main`. If not, the `cplace-asc` is not able to compile the platform plugins:

```
error TS6059: File '/Users/bdries/Documents/cPlace/repos/main/cf.cplace.platform/assets/ts/serverLog.ts' is not under 'rootDir' '/Users/bdries/Documents/cPlace/repos/cplaceFork/cf.cplace.platform/assets/ts'. 'rootDir' is expected to contain all source files.

error TS6059: File '/Users/bdries/Documents/cPlace/repos/main/cf.cplace.platform/assets/ts/xhrIntercept.ts' is not under 'rootDir' '/Users/bdries/Documents/cPlace/repos/cplaceFork/cf.cplace.platform/assets/ts'. 'rootDir' is expected to contain all source files.
```

**Comment by csemrau** [comment]
Naming the `cplace` repository anything other than `main` is not supported by cplace. It may break other tools as well, and make for confusing IDEA project configuration differences.

If you want to use a fork of the repo (or just a second working copy cloned from the same remote repo), use a new `repos` folder to contain the `main` folder of the forked repo. E.g. you would have folders

    .../repos/main - the standard cplace repo
    .../repos/cplace-project-planning - the standard cplace-project-planning repo
    .../reposForked/main - the forked cplace repo
